# Generated by Django 3.1 on 2024-09-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('variation_category', 'variation_value')},
        ),
    ]
